"""Allow activation_token to be nullable

Revision ID: 060e2a6aff61
Revises: 121a26450433
Create Date: 2026-08-02 20:01:54.872434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060e2a6aff61'
down_revision = '121a26450433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('activation_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('activation_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
