"""Add project upload and visibility system

Revision ID: 2f1c17012a18
Revises: df30e058c669
Create Date: 2026-08-04 15:50:10.138397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1c17012a18'
down_revision = 'df30e058c669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_file', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=30), nullable=False))
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('visibility')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
        batch_op.drop_column('project_file')

    # ### end Alembic commands ###
