"""Add extended user profile fields

Revision ID: 99bade84aafd
Revises: d8e932558ae3
Create Date: 2026-08-03 19:41:46.423145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bade84aafd'
down_revision = 'd8e932558ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('socket_id', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('message_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_reader')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('chat_messages_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('chat_messages_team_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'chat_channels', ['channel_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('message')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('link')
        batch_op.drop_column('type')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_messages_team_id_fkey'), 'teams', ['team_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('chat_messages_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('deleted')
        batch_op.drop_column('edited')
        batch_op.drop_column('content')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('channel_id')

    op.drop_table('message_reads')
    op.drop_table('user_presence')
    op.drop_table('chat_channels')
    # ### end Alembic commands ###
