"""Add profile information to users

Revision ID: d90579372706
Revises: 060e2a6aff61
Create Date: 2026-08-02 20:28:14.536251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90579372706'
down_revision = '060e2a6aff61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portfolio', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tryhackme', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hackthebox', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ctftime', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ctftime')
        batch_op.drop_column('hackthebox')
        batch_op.drop_column('tryhackme')
        batch_op.drop_column('twitter')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('github')
        batch_op.drop_column('portfolio')
        batch_op.drop_column('skills')
        batch_op.drop_column('company')
        batch_op.drop_column('job_title')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
