"""Add missing profile columns to users

Revision ID: df30e058c669
Revises: 99bade84aafd
Create Date: 2026-08-03 19:55:19.369267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df30e058c669'
down_revision = '99bade84aafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('favorite_language', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_language')
        batch_op.drop_column('experience_level')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
